name: Emulator Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       sudo apt install android-sdk
       ls -la /home/runner/
