name: Install and run Emulator via CURL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Android-Build-and-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       sudo apt-get update
       # sudo apt-get install libpulse0
       sudo apt-get install unzip
       curl https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o /home/runner/commandlinetools-linux-9477386_latest.zip
       unzip /home/runner/commandlinetools-linux-9477386_latest.zip -d /home/runner/cmdline-tools
       sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest/
       sudo cp -a /home/runner/cmdline-tools/cmdline-tools/. /usr/local/lib/android/sdk/cmdline-tools/latest/
       echo "copying cmdline tools over"
       ls -la /usr/local/lib/android/sdk/
       pwd
       ls -la 
       ls -la /home/runner/
    - name: Build 
      run: ./gradlew build
    - name: Setup Emulator
      run: | 
       /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --list
       ls -la /home/runner/
       ls -la /home/runner/cmdline-tools/
       yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
       /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
       echo "no" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name "pixel_5_api30_google_apis_emulator" --abi google_apis/x86_64 --package "system-images;android-30;google_apis;x86_64" --device "pixel_5"
       /usr/local/lib/android/sdk/emulator/emulator -list-avds
       /usr/local/lib/android/sdk/emulator/emulator -avd pixel_5_api30_google_apis_emulator
