name: Android CI with SDK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install Android Sdk
      run: sudo apt update && sudo apt install android-sdk 
    - name: Echo javahome
      run: yes | sdkmanager "platforms;android-24" 
    - name: Build with Gradle
      run: ./gradlew build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
