name: Install and run Emulator via CURL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
     
       sudo apt-get update
       sudo apt-get install unzip
       curl https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /home/runner/commandlinetools-linux-9477386_latest.zip
       unzip /home/runner/commandlinetools-linux-9477386_latest.zip
       pwd
       ls -la 
       ls -la /home/runner/
