name: Android CI with SDK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       pwd
       sudo snap install androidsdk
       export ANDROID_SDK_ROOT=/home/runner/AndroidSDK/
       pwd
    - name: Install android SDK
      run: |
       yes | androidsdk "platforms;android-24" 
       yes | androidsdk "platform-tools" 
       yes | androidsdk "emulator" 
       yes | androidsdk "cmdline-tools;latest"
       yes | androidsdk "system-images;android-23;google_apis;x86_64"
       androidsdk --list
       ls -la /home/runner/AndroidSDK/
       ls -la /home/runner/AndroidSDK/cmdline-tools/latest/bin
       ls -la /home/runner/AndroidSDK/emulator 
    - name: Build with Gradle
      run: |
       export ANDROID_SDK_ROOT=/home/runner/AndroidSDK/
       export ANDROID_HOME=/home/runner/AndroidSDK/ && ./gradlew build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: AVD Setup
      run: echo no | /home/runner/AndroidSDK/cmdline-tools/latest/bin/avdmanager create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-23;google_apis;x86_64' 
    - name: Emulator Test
      run: | 
       export ANDROID_AVD_HOME=/home/runner/.android/avd/
       export ANDROID_SDK_HOME=/home/runner/AndroidSDK/
       export ANDROID_SDK_ROOT=/home/runner/AndroidSDK/ && /home/runner/AndroidSDK/emulator/emulator -avd testAVD -no-audio -no-boot-anim -no-window -accel-on -gpu-off 
