name: Android CI with SDK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       pwd
       sudo snap install androidsdk
       
       export ANDROID_SDK_PATH=/home/runner/AndroidSDK
       pwd
    - name: Install android SDK
      run: |
       yes | androidsdk "platforms;android-24" 
       ls -la /home/runner/AndroidSDK 
    - name: Build with Gradle
      run: ./gradlew build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
