name: Install and run Emulator via CURL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Android-Build-and-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       sudo apt-get update
       sudo apt-get install unzip
       curl https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o /home/runner/commandlinetools-linux-9477386_latest.zip
       unzip /home/runner/commandlinetools-linux-9477386_latest.zip -d /home/runner/cmdline-tools
       pwd
       ls -la 
       ls -la /home/runner/
    - name: Build 
      run: ./gradlew build
    - name: Setup Emulator
      run: | 
       /home/runner/cmdline-tools/cmdline-tools/bin/sdkmanager --list
       ls -la /home/runner/
       ls -la /home/runner/cmdline-tools/
       echo "yes" | /home/runner/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
       /home/runner/cmdline-tools/cmdline-tools/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
       echo "no" | /home/runner/cmdline-tools/cmdline-tools/bin/avdmanager --verbose create avd --force --name "pixel_5_api30_google_apis_emulator" --package "system-images;android-30;google_apis;x86_64" --tag "google_api" --device "pixel_5"
