name: Install and run Emulator via CURL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Android-Build-and-Test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Echo javahome
      run: echo $JAVA_HOME
    - name: Install SDK Manager
      run: |
       brew tap homebrew/cask
       brew install --cask android-sdk
    - name: Build 
      run: ./gradlew build
    - name: Setup Emulator
      run: | 
       sdkmanager --list
       yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
       sdkmanager --install "system-images;android-30;google_apis;x86_64"
       sdkmanager --install "system-images;android-30;google_apis;x86"
       echo "no" | avdmanager --verbose create avd --force --name "pixel_5_api30_google_apis_emulator_x86" --abi google_apis/x86 --package "system-images;android-30;google_apis;x86" --device "pixel_5"
       echo "no" | avdmanager --verbose create avd --force --name "pixel_5_api30_google_apis_emulator" --abi google_apis/x86_64 --package "system-images;android-30;google_apis;x86_64" --device "pixel_5"
       emulator -list-avds
       emulator -avd pixel_5_api30_google_apis_emulator_x86
       emulator -avd pixel_5_api30_google_apis_emulator
